spring:
 application:
   name: ingredient-service
 datasource:
   url: jdbc:h2:mem:testdb  # Użycie bazy danych H2 w pamięci
   driver-class-name: org.h2.Driver
   username: sa
   password: password
   h2:
     console:
       enabled: true  # Włącza konsolę H2 dostępna pod adresem /h2-console
   jpa:
     hibernate:
       ddl-auto: update  # Automatyczne aktualizowanie schematu bazy danych
     database-platform: org.hibernate.dialect.H2Dialect

server:
 port: 0

eureka:
 client:
   service-url:
     defaultZone: http://localhost:8761/eureka/